
##############################################################
# This Script has been generated by Ixia ScriptGen
#      Software Version : IxExplorer 10.80.8001.21 Patch2         
##############################################################


package req IxTclHal

# Command Option Mode - Comment (generate commented commands for default values)


if {[isUNIX]} {
	if {[ixConnectToTclServer 10.89.83.99]} {
		errorMsg "Error connecting to Tcl Server 10.89.83.99 "
		return $::TCL_ERROR
	}
}


######### Chassis- 10.89.83.99 #########

ixConnectToChassis   {10.89.83.99}

chassis get "10.89.83.99"
set chassis	  [chassis cget -id]
set card     1
set port     2
set portList {}
set portStr  10.89.83.99/1/2.1
set cardStr  10.89.83.99/1

######### Card Type : 800GE-8P-OSFP-M+NRZ ############

# card setDefault 
# #card config -txFrequencyDeviation 0
# set retCode [card set $chassis $card]
# switch $retCode \
# 	$::TCL_OK { \
# 		if { [card write $chassis $card] != $::TCL_OK } { \
# 			errorMsg "Error calling card write $chassis $card"; \
# 			set retCode $::TCL_ERROR; \
# 		} \
# 	} \
# 	$::ixTcl_notAvailable { \
# 		logMsg "One or more of the ports on this card is unavailable, please check ownership. Card settings not applied."; \
# 	} \
# 	default { \
# 		errorMsg "Error calling card set $chassis $card"; \
# 	}

######### Chassis-10.89.83.99 Card-1  Port-2 #########

resourceGroupEx get $chassis $card $port
resourceGroupEx config -activeCapturePortList              "{0 1 2}"
resourceGroupEx config -activePortList                     "{0 1 2}"
resourceGroupEx config -resourcePortList                   "{0 1 2} {0 1 11} {0 1 12} {0 1 29} {0 1 30} {0 1 31} {0 1 32} {0 1 65} {0 1 66} {0 1 67} {0 1 68} {0 1 69} {0 1 70} {0 1 71} {0 1 72} {0 1 122} {0 1 131} {0 1 132} {0 1 149} {0 1 150} {0 1 151} {0 1 152} {0 1 185} {0 1 186} {0 1 187} {0 1 188} {0 1 189} {0 1 190} {0 1 191} {0 1 192} {0 1 242} {0 1 251} {0 1 252} {0 1 269} {0 1 270} {0 1 271} {0 1 272} {0 1 305} {0 1 306} {0 1 307} {0 1 308} {0 1 309} {0 1 310} {0 1 311} {0 1 312} {0 1 363} {0 1 364} {0 1 385} {0 1 386} {0 1 387} {0 1 388} {0 1 389} {0 1 390} {0 1 391} {0 1 392}"
#resourceGroupEx config -ppm 0
resourceGroupEx config -mode                               800000
resourceGroupEx config -attributes                         "{serdesModePam4}"
#resourceGroupEx config -hidePortMode 0
resourceGroupEx config -modeName                           "800G-R8"
if {[resourceGroupEx  set $chassis $card $port]} {
	errorMsg "Error calling resourceGroupEx  set $chassis $card $port"
	set retCode $::TCL_ERROR
}

if {[resourceGroupEx write $chassis $card $port]} {
	errorMsg "Error calling resourceGroupEx write $chassis $card $port"
	set retCode $::TCL_ERROR
}

port setFactoryDefaults $chassis $card $port
port config -speed                              800000
#port config -duplex full
port config -flowControl                        true
#port config -directedAddress  "01 80 C2 00 00 01"
#port config -multicastPauseAddress  "01 80 C2 00 00 01"
#port config -loopback portNormal
port config -transmitMode                       portTxModeAdvancedScheduler
port config -receiveMode                        [expr $::portCapture|$::portRxDataIntegrity|$::portRxSequenceChecking|$::portRxModeWidePacketGroup]
port config -autonegotiate                      true
port config -advertise100FullDuplex             false
port config -advertise100HalfDuplex             false
port config -advertise10FullDuplex              false
port config -advertise10HalfDuplex              false
#port config -advertise1000FullDuplex false
#port config -advertise5FullDuplex false
#port config -advertise2P5FullDuplex false
#port config -advertise10MFullDuplex false
#port config -portMode portEthernetMode
#port config -enableDataCenterMode false
port config -dataCenterMode                     fourPriorityTrafficMapping
#port config -flowControlType ieee8023x
#port config -pfcEnableValueListBitMatrix  ""
#port config -pfcResponseDelayEnabled 0
#port config -pfcResponseDelayQuanta 0
#port config -rxTxMode gigNormal
#port config -ignoreLink false
#port config -advertiseAbilities portAdvertiseNone
#port config -timeoutEnable true
#port config -negotiateMasterSlave 0
#port config -masterSlave portSlave
#port config -pmaClock pmaClockAutoNegotiate
#port config -enableSimulateCableDisconnect false
port config -enableAutoDetectInstrumentation    true
port config -autoDetectInstrumentationMode      portAutoInstrumentationModeFloating
#port config -enableRepeatableLastRandomPattern false
#port config -transmitClockDeviation 0
#port config -transmitClockMode portClockInternal
#port config -preEmphasis preEmphasis0
port config -transmitExtendedTimestamp          1
#port config -enableFramePreemption false
#port config -enableSmdVRExchange false
#port config -operationModeList  [list]
#port config -MacAddress  "00 de bb 00 00 01"
#port config -DestMacAddress  "00 de bb 00 00 02"
#port config -name  ""
#port config -numAddresses 1
#port config -enableManualAutoNegotiate false
#port config -enablePhyPolling true
#port config -enableTxRxSyncStatsMode false
#port config -txRxSyncInterval 0
#port config -enableTransparentDynamicRateChange false
#port config -enableDynamicMPLSMode false
#port config -enablePortCpuFlowControl false
#port config -portCpuFlowControlDestAddr  "01 80 C2 00 00 01"
#port config -portCpuFlowControlSrcAddr  "00 00 01 00 02 00"
#port config -portCpuFlowControlPriority  "0 0 0 0 0 0 0 0"
#port config -portCpuFlowControlType 0
#port config -enableWanIFSStretch false
#port config -enableRestartStream false
port config -enableRxNonIEEEPreamble            true
#port config -enableRsFec false
#port config -enableRsFecStats false
port config -enableLinkTraining                 true
port config -ieeeL1Defaults                     1
#port config -firecodeRequest 0
#port config -firecodeAdvertise 0
#port config -firecodeForceOn 0
#port config -firecodeForceOff 0
#port config -reedSolomonRequest 0
#port config -reedSolomonAdvertise 0
#port config -reedSolomonForceOn 0
#port config -reedSolomonForceOff 0
#port config -autoCtleAdjustment 0
#port config -overrideLtTapSettings 0
port config -negotiatedCapability               "Status: Complete

Result: Autoneg Success:  IEEE 800GBASE-CR8/KR8, PAUSE TX+RX, RS-FEC; Advertised: ETC 800G-CR8, IEEE 800G-CR8; Received: ETC 800G-CR8, IEEE 800G-CR8"
#port config -am100GTwoLane 0
#port config -anPreset 0
#port config -requestRsFecInt 0
#port config -fecOption 0
#port config -enablePLCA false
#port config -plcaNodeID 0
#port config -plcaMaxNodeCount 0
#port config -plcaBurstCount 0
#port config -plcaBurstTimer 0
#port config -plcaToTimer 0
#port config -plcaMacTSLatencyMode 0
if {[port set $chassis $card $port]} {
	errorMsg "Error calling port set $chassis $card $port"
	set retCode $::TCL_ERROR
}

stat setDefault 
#stat config -mode statNormal
#stat config -enableValidStats false
#stat config -enableProtocolServerStats true
#stat config -enableArpStats true
#stat config -enablePosExtendedStats true
#stat config -enableDhcpStats false
#stat config -enableDhcpV6Stats false
#stat config -enableEthernetOamStats false
#stat config -enableFcoeStats false
#stat config -fcoeRxSharedStatType1 statFcoeValidFrames
#stat config -fcoeRxSharedStatType2 statFcoeValidFrames
#stat config -enableLldpDcbxStats false
stat config -enableBgpStats                     false
#stat config -enableIcmpStats true
stat config -enableOspfStats                    false
stat config -enableIsisStats                    false
stat config -enableRsvpStats                    false
stat config -enableLdpStats                     false
stat config -enableIgmpStats                    false
stat config -enableOspfV3Stats                  false
stat config -enablePimsmStats                   false
stat config -enableMldStats                     false
stat config -enableStpStats                     false
stat config -enableEigrpStats                   false
stat config -enableBfdStats                     false
stat config -enableCfmStats                     false
stat config -enableLacpStats                    false
stat config -enableOamStats                     false
stat config -enableMplsTpStats                  false
stat config -enableElmiStats                    false
if {[stat set $chassis $card $port]} {
	errorMsg "Error calling stat set $chassis $card $port"
	set retCode $::TCL_ERROR
}

kp4FecError setDefault 
#kp4FecError config -type 0
#kp4FecError config -berCoefficient 1.0
#kp4FecError config -berExponent 8
#kp4FecError config -berDistribution 50
#kp4FecError config -repeat 0
#kp4FecError config -loopcount 1
#kp4FecError config -symbolErrorCount 1
#kp4FecError config -symbolCorrectCount 0
#kp4FecError config -symbolErrorPerCodeword 1
#kp4FecError config -laneNumber 1
#kp4FecError config -errorBits 10
if {[kp4FecError set $chassis $card $port]} {
	errorMsg "Error calling kp4FecError set $chassis $card $port"
	set retCode $::TCL_ERROR
}


packetGroup setDefault 
#packetGroup config -signatureOffset 48
#packetGroup config -signature  "08 71 18 05"
#packetGroup config -insertSignature false
#packetGroup config -ignoreSignature false
#packetGroup config -groupId 0
#packetGroup config -groupIdOffset 52
#packetGroup config -enableGroupIdMask false
#packetGroup config -enableInsertPgid true
packetGroup config -groupIdMask                        4294934528
#packetGroup config -latencyControl cutThrough
#packetGroup config -measurementMode packetGroupModeLatency
#packetGroup config -delayVariationMode delayVariationWithSequenceErrors
#packetGroup config -preambleSize 8
#packetGroup config -sequenceNumberOffset 44
#packetGroup config -sequenceErrorThreshold 2
#packetGroup config -insertSequenceSignature false
#packetGroup config -allocateUdf true
#packetGroup config -enableSignatureMask false
#packetGroup config -signatureMask  "00 00 00 00"
#packetGroup config -enableRxFilter false
#packetGroup config -headerFilter  "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"
#packetGroup config -headerFilterMask  "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"
packetGroup config -enable128kBinMode                  true
#packetGroup config -enableTimeBins false
#packetGroup config -numPgidPerTimeBin 32
packetGroup config -numTimeBins                        1
#packetGroup config -timeBinDuration 1000000
#packetGroup config -enableLatencyBins false
#packetGroup config -latencyBinList  ""
#packetGroup config -enableSizeBins false
#packetGroup config -sizeBinList  ""
#packetGroup config -groupIdMode packetGroupCustom
#packetGroup config -sequenceCheckingMode seqThreshold
#packetGroup config -multiSwitchedPathMode seqSwitchedPathPGID
#packetGroup config -pgidStatMode 0
#packetGroup config -enableLastBitTimeStamp false
#packetGroup config -seqAdvTrackingLateThreshold 1000
#packetGroup config -enableReArmFirstTimeStamp false
if {[packetGroup setRx $chassis $card $port]} {
	errorMsg "Error calling packetGroup setRx $chassis $card $port"
	set retCode $::TCL_ERROR
}


dataIntegrity setDefault 
#dataIntegrity config -signatureOffset 40
dataIntegrity config -signature                          "08 71 18 00"
#dataIntegrity config -insertSignature false
dataIntegrity config -enableTimeStamp                    true
#dataIntegrity config -floatingTimestampAndDataIntegrityMode dataIntegrityNumberOfBytesFromEndOfFrame
#dataIntegrity config -numBytesFromEndOfFrame 4
#dataIntegrity config -payloadLength 0
if {[dataIntegrity setRx $chassis $card $port]} {
	errorMsg "Error calling dataIntegrity setRx $chassis $card $port"
	set retCode $::TCL_ERROR
}

autoDetectInstrumentation setDefault 
autoDetectInstrumentation config -startOfScan                        8
#autoDetectInstrumentation config -signature  {87 73 67 49 42 87 11 80 08 71 18 05}
#autoDetectInstrumentation config -enableSignatureMask false
#autoDetectInstrumentation config -signatureMask  {00 00 00 00 00 00 00 00 00 00 00 00}
if {[autoDetectInstrumentation setRx $chassis $card $port]} {
	errorMsg "Error calling autoDetectInstrumentation setRx $chassis $card $port"
	set retCode $::TCL_ERROR
}

linkFaultSignaling setDefault 
#linkFaultSignaling config -contiguousErrorBlocks 4
#linkFaultSignaling config -contiguousGoodBlocks 0
#linkFaultSignaling config -sendSetsMode linkFaultAlternateOrderedSets
#linkFaultSignaling config -loopCount 1
#linkFaultSignaling config -enableLoopContinuously true
#linkFaultSignaling config -enableTxIgnoresRxLinkFault false
#linkFaultSignaling config -orderedSetTypeA linkFaultLocal
#linkFaultSignaling config -orderedSetTypeB linkFaultRemote
if {[linkFaultSignaling set $chassis $card $port]} {
	errorMsg "Error calling linkFaultSignaling set $chassis $card $port"
	set retCode $::TCL_ERROR
}


filter setDefault 
#filter config -captureTriggerDA anyAddr
#filter config -captureTriggerSA anyAddr
#filter config -captureTriggerPattern anyPattern
#filter config -captureTriggerError errAnyFrame
#filter config -captureTriggerFrameSizeEnable false
filter config -captureTriggerFrameSizeFrom        61
filter config -captureTriggerFrameSizeTo          61
#filter config -captureTriggerCircuit filterAnyCircuit
#filter config -captureFilterDA anyAddr
#filter config -captureFilterSA anyAddr
#filter config -captureFilterPattern anyPattern
#filter config -captureFilterError errAnyFrame
#filter config -captureFilterFrameSizeEnable false
filter config -captureFilterFrameSizeFrom         61
filter config -captureFilterFrameSizeTo           61
#filter config -captureFilterCircuit filterAnyCircuit
#filter config -userDefinedStat1DA anyAddr
#filter config -userDefinedStat1SA anyAddr
#filter config -userDefinedStat1Pattern anyPattern
#filter config -userDefinedStat1Error errAnyFrame
#filter config -userDefinedStat1FrameSizeEnable false
filter config -userDefinedStat1FrameSizeFrom      61
filter config -userDefinedStat1FrameSizeTo        61
#filter config -userDefinedStat1Circuit filterAnyCircuit
#filter config -userDefinedStat2DA anyAddr
#filter config -userDefinedStat2SA anyAddr
#filter config -userDefinedStat2Pattern anyPattern
#filter config -userDefinedStat2Error errAnyFrame
#filter config -userDefinedStat2FrameSizeEnable 0
filter config -userDefinedStat2FrameSizeFrom      61
filter config -userDefinedStat2FrameSizeTo        61
#filter config -userDefinedStat2Circuit filterAnyCircuit
#filter config -asyncTrigger1DA anyAddr
#filter config -asyncTrigger1SA anyAddr
#filter config -asyncTrigger1Pattern anyPattern
#filter config -asyncTrigger1Error errAnyFrame
#filter config -asyncTrigger1FrameSizeEnable false
filter config -asyncTrigger1FrameSizeFrom         61
filter config -asyncTrigger1FrameSizeTo           61
#filter config -asyncTrigger1Circuit filterAnyCircuit
#filter config -asyncTrigger2DA anyAddr
#filter config -asyncTrigger2SA anyAddr
#filter config -asyncTrigger2Pattern anyPattern
#filter config -asyncTrigger2Error errAnyFrame
#filter config -asyncTrigger2FrameSizeEnable false
filter config -asyncTrigger2FrameSizeFrom         61
filter config -asyncTrigger2FrameSizeTo           61
#filter config -asyncTrigger2Circuit filterAnyCircuit
#filter config -captureTriggerEnable true
#filter config -captureFilterEnable true
#filter config -userDefinedStat1Enable false
#filter config -userDefinedStat2Enable false
#filter config -asyncTrigger1Enable false
#filter config -asyncTrigger2Enable false
#filter config -userDefinedStat1PatternExpressionEnable false
#filter config -userDefinedStat2PatternExpressionEnable false
#filter config -captureTriggerPatternExpressionEnable false
#filter config -captureFilterPatternExpressionEnable false
#filter config -asyncTrigger1PatternExpressionEnable false
#filter config -asyncTrigger2PatternExpressionEnable false
filter config -userDefinedStat1PatternExpression  ""
filter config -userDefinedStat2PatternExpression  ""
filter config -captureTriggerPatternExpression    ""
filter config -captureFilterPatternExpression     ""
filter config -asyncTrigger1PatternExpression     ""
filter config -asyncTrigger2PatternExpression     ""
if {[filter set $chassis $card $port]} {
	errorMsg "Error calling filter set $chassis $card $port"
	set retCode $::TCL_ERROR
}


filterPallette setDefault 
#filterPallette config -DA1  "00 00 00 00 00 00"
#filterPallette config -DAMask1  "00 00 00 00 00 00"
#filterPallette config -DA2  "00 00 00 00 00 00"
#filterPallette config -DAMask2  "00 00 00 00 00 00"
#filterPallette config -SA1  "00 00 00 00 00 00"
#filterPallette config -SAMask1  "00 00 00 00 00 00"
#filterPallette config -SA2  "00 00 00 00 00 00"
#filterPallette config -SAMask2  "00 00 00 00 00 00"
#filterPallette config -pattern1  "DE ED EF FE AC CA"
#filterPallette config -patternMask1  "00 00 00 00 00 00"
#filterPallette config -pattern2 00
#filterPallette config -patternMask2 00
#filterPallette config -pattern3  ""
#filterPallette config -patternMask3  ""
#filterPallette config -pattern4  ""
#filterPallette config -patternMask4  ""
#filterPallette config -patternOffset1 12
#filterPallette config -patternOffset2 12
#filterPallette config -patternOffset3 0
#filterPallette config -patternOffset4 0
#filterPallette config -matchType1 matchUser
#filterPallette config -matchType2 matchUser
#filterPallette config -matchType3 3
#filterPallette config -matchType4 3
#filterPallette config -patternOffsetType1 filterPalletteOffsetStartOfFrame
#filterPallette config -patternOffsetType2 filterPalletteOffsetStartOfFrame
#filterPallette config -patternOffsetType3 0
#filterPallette config -patternOffsetType4 0
#filterPallette config -gfpErrorCondition gfpErrorsOr
#filterPallette config -enableGfptHecError true
#filterPallette config -enableGfpeHecError true
#filterPallette config -enableGfpPayloadCrcError true
#filterPallette config -enableGfpBadFcsError true
#filterPallette config -circuitList  ""
filterPallette config -range1Min                          61
filterPallette config -range1Max                          61
filterPallette config -range2Min                          61
filterPallette config -range2Max                          61
filterPallette config -range3Min                          61
filterPallette config -range3Max                          61
filterPallette config -range4Min                          61
filterPallette config -range4Max                          61
#filterPallette config -range1MatchMinMaxOnly 0
#filterPallette config -range2MatchMinMaxOnly 0
#filterPallette config -range3MatchMinMaxOnly 0
#filterPallette config -range4MatchMinMaxOnly 0
if {[filterPallette set $chassis $card $port]} {
	errorMsg "Error calling filterPallette set $chassis $card $port"
	set retCode $::TCL_ERROR
}

capture setDefault 
#capture config -fullAction lock
capture config -sliceSize                          16384
#capture config -sliceOffset 0
#capture config -captureMode captureTriggerMode
#capture config -continuousFilter 0
#capture config -beforeTriggerFilter captureBeforeTriggerNone
#capture config -afterTriggerFilter captureAfterTriggerFilter
#capture config -triggerPosition 1.0
#capture config -enableSmallPacketCapture false
#capture config -captureDirection 0
if {[capture set $chassis $card $port]} {
	errorMsg "Error calling capture set $chassis $card $port"
	set retCode $::TCL_ERROR
}

txRxPreamble setDefault 
txRxPreamble config -txMode                             preambleByteCount
txRxPreamble config -rxMode                             preambleByteCount
#txRxPreamble config -txPreambleSize 8
#txRxPreamble config -rxPreambleSize 8
#txRxPreamble config -enableCiscoCDL false
#txRxPreamble config -enablePreambleView false
#txRxPreamble config -enableCDLStats false
#txRxPreamble config -enableIncludePreambleInRxCrc false
#txRxPreamble config -enableEditablePreambleMode false
if {[txRxPreamble set $chassis $card $port]} {
	errorMsg "Error calling txRxPreamble set $chassis $card $port"
	set retCode $::TCL_ERROR
}



if {[interfaceTable select $chassis $card $port]} {
	errorMsg "Error calling interfaceTable select $chassis $card $port"
	set retCode $::TCL_ERROR
}

interfaceTable setDefault 
#interfaceTable config -dhcpV4RequestRate 0
#interfaceTable config -dhcpV6RequestRate 0
#interfaceTable config -dhcpV4MaximumOutstandingRequests 100
#interfaceTable config -dhcpV6MaximumOutstandingRequests 100
#interfaceTable config -fcoeRequestRate 500
#interfaceTable config -fcoeNumRetries 5
#interfaceTable config -fcoeRetryInterval 2000
#interfaceTable config -fipVersion fipVersion1
#interfaceTable config -enableFcfMac false
#interfaceTable config -fcfMacCollectionTime 1000
#interfaceTable config -enablePMacInFpma true
#interfaceTable config -enableNameIdInVLANDiscovery false
#interfaceTable config -enableTargetLinkLayerAddrOption false
#interfaceTable config -enableAutoNeighborDiscovery false
#interfaceTable config -enableAutoArp false
if {[interfaceTable set]} {
	errorMsg "Error calling interfaceTable set"
	set retCode $::TCL_ERROR
}

interfaceTable clearAllInterfaces 
if {[interfaceTable write]} {
	errorMsg "Error calling interfaceTable write"
	set retCode $::TCL_ERROR
}


protocolServer setDefault 
#protocolServer config -enableArpResponse false
#protocolServer config -enablePingResponse false
if {[protocolServer set $chassis $card $port]} {
	errorMsg "Error calling protocolServer set $chassis $card $port"
	set retCode $::TCL_ERROR
}


oamPort setDefault 
#oamPort config -enable false
oamPort config -macAddress                         "00 00 AB BA DE AD"
#oamPort config -enableLoopback false
#oamPort config -enableLinkEvents false
#oamPort config -maxOamPduSize 1518
#oamPort config -oui  "00 00 00"
#oamPort config -vendorSpecificInformation  "00 00 00 00"
#oamPort config -idleTimer 5
#oamPort config -enableOptionalTlv false
#oamPort config -optionalTlvType 254
#oamPort config -optionalTlvValue  ""
if {[oamPort set $chassis $card $port]} {
	errorMsg "Error calling oamPort set $chassis $card $port"
	set retCode $::TCL_ERROR
}

ixEnablePortIntrinsicLatencyAdjustment $chassis $card $port true
lappend portList [list $chassis $card $port]

ixWritePortsToHardware portList
ixCheckLinkState portList

######### Chassis-10.89.83.99 Card-1  Port-2 #########

streamRegion get $chassis $card $port
if {[streamRegion enableGenerateWarningList  $chassis $card $port 0]} {
	errorMsg "Error calling streamRegion enableGenerateWarningList  $chassis $card $port 0"
	set retCode $::TCL_ERROR
}

set streamId 1

if {[port resetStreamProtocolStack $chassis $card $port]} {
	errorMsg "Error calling port resetStreamProtocolStack $chassis $card $port"
	set retCode $::TCL_ERROR
}

#  Stream 1
stream setDefault 
#stream config -name  ""
#stream config -enable true
#stream config -enableSuspend false
#stream config -region 0
#stream config -numBursts 1
#stream config -numFrames 100
stream config -ifg                                0.12
#stream config -ifgType gapFixed
stream config -ifgMIN                             0.24
stream config -ifgMAX                             0.32
stream config -ibg                                163.12
#stream config -enableIbg false
stream config -isg                                0.0
#stream config -enableIsg false
#stream config -gapUnit gapNanoSeconds
#stream config -percentPacketRate 100.0
stream config -fpsRate                            1190476190.4761906
stream config -bpsRate                            609523809523.8096
#stream config -rateMode streamRateModePercentRate
#stream config -preambleSize 8
stream config -preambleData                       "55 55 55 55 55 55 D5"
stream config -sa                                 "00 00 00 00 01 00"
#stream config -saRepeatCounter idle
#stream config -saStep 1
#stream config -saMaskValue  "00 00 00 00 00 00"
stream config -saMaskSelect                       "FF FF 00 00 00 00"
#stream config -enableSaContinueFromLastValue false
#stream config -da  "00 00 00 00 00 00"
#stream config -daRepeatCounter idle
#stream config -daStep 1
#stream config -daMaskValue  "00 00 00 00 00 00"
stream config -daMaskSelect                       "FF FF 00 00 00 00"
#stream config -enableDaContinueFromLastValue false
#stream config -framesize 64
#stream config -frameSizeType sizeFixed
#stream config -frameSizeMIN 64
#stream config -frameSizeMAX 64
#stream config -frameSizeStep 1
#stream config -enableTimestamp false
#stream config -fcs good
#stream config -patternType incrByte
#stream config -dataPattern x00010203
#stream config -pattern  "00 01 02 03"
stream config -frameType                          "FF FF"
stream config -numDA                              16
stream config -numSA                              16
#stream config -dma contPacket
#stream config -rxTriggerEnable false
stream config -asyncIntEnable                     true
#stream config -loopCount 1
#stream config -returnToId 1
#stream config -enforceMinGap 12
#stream config -enableStatistic true
#stream config -enableIncrFrameBurstOverride false
#stream config -enableDisparityError false
#stream config -forceDisableDataMangling 0
#stream config -enableSourceInterface false
#stream config -sourceInterfaceDescription  ""
#stream config -startTxDelayUnit 4
#stream config -startTxDelay 0.0
#stream config -priorityGroup priorityGroup0

protocol setDefault 
#protocol config -name mac
#protocol config -appName noType
#protocol config -ethernetType noType
#protocol config -enable802dot1qTag vlanNone
#protocol config -enableISLtag false
#protocol config -enableMPLS false
#protocol config -enableMacSec false
#protocol config -enableOAM false
#protocol config -enableDataCenterEncapsulation false
#protocol config -enableProtocolPad false




if {[port isValidFeature $chassis $card $port $::portFeatureRandomFrameSizeWeightedPair]} { 
	weightedRandomFramesize setDefault
	if {[weightedRandomFramesize set $chassis $card $port]} {
		errorMsg "Error calling weightedRandomFramesize set $chassis $card $port"
		set retCode $::TCL_ERROR
	}

}

if {[stream set $chassis $card $port $streamId]} {
	errorMsg "Error calling stream set $chassis $card $port $streamId"
	set retCode $::TCL_ERROR
}

incr streamId
streamRegion generateWarningList $chassis $card $port
ixWriteConfigToHardware portList -noProtocolServer
